export enum WalletTransactionType {
  JOB_CREDIT = 'JOB_CREDIT',
  COMMISSION_DEBIT = 'COMMISSION_DEBIT',
  INSPECTION_FEE_CREDIT = 'INSPECTION_FEE_CREDIT',
  PAYOUT = 'PAYOUT',
  REFUND = 'REFUND',
}